# Refer to Bunny's new connection parameters for settings here.
# http://rubybunny.info/articles/connecting.html

defaults: &defaults
  host: localhost

development:
  <<: *defaults

test:
  <<: *defaults
