# Refer to Bunny's new connection parameters for settings here.
# http://rubybunny.info/articles/connecting.html

defaults: &defaults
  host: localhost
  port: 5672
  ssl: false
  user: guest
  pass: guest
  threaded: false

development:
  <<: *defaults

test:
  <<: *defaults
